import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTableModule } from '@angular/material/table';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatChipsModule } from '@angular/material/chips';
import { FormsModule } from '@angular/forms';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { Subject, debounceTime, distinctUntilChanged, finalize } from 'rxjs';
import { InspectionQICReportService, InspectionQICReportPayload } from '../../../../core/services/inspection-qic-report.service';
import { AuthService } from '../../../../core/services/auth.service';
import { computed } from '@angular/core';

@Component({
  selector: 'app-quality-inspection-reports',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    MatTableModule,
    MatPaginatorModule,
    MatFormFieldModule,
    MatInputModule,
    MatTooltipModule,
    MatChipsModule,
    FormsModule,
    MatProgressBarModule
  ],
  template: `
    <div class="reports-container">
      <div class="glass-header">
        <div class="header-content">
          <div class="title-section">
            <mat-icon class="feature-icon">assessment</mat-icon>
            <div class="text-group">
              <h1>Quality Inspection Reports</h1>
              <p>Manage and monitor all QIC inspection batches</p>
            </div>
          </div>
          
          <div class="actions-section">
            <div class="search-box">
              <mat-icon>search</mat-icon>
              <input type="text" placeholder="Search Report #..." 
                     [(ngModel)]="searchQuery" (ngModelChange)="onSearchChange()">
            </div>
          </div>
        </div>
      </div>

      <div class="content-area">
        <div class="table-card">
          <mat-progress-bar mode="indeterminate" color="primary" *ngIf="isLoading()"
                            style="position: absolute; top: 0; left: 0; right: 0; z-index: 10; height: 3px;">
          </mat-progress-bar>

          <table mat-table [dataSource]="reports()" class="luxe-table" [class.loading-fade]="isLoading()">
            
            <ng-container matColumnDef="reportNo">
              <th mat-header-cell *matHeaderCellDef>Report #</th>
              <td mat-cell *matCellDef="let report">
                <div class="report-id">
                  <span class="prefix">QIC</span>
                  <strong>{{ report.reportNumber }}</strong>
                </div>
              </td>
            </ng-container>

            <ng-container matColumnDef="generatedAt">
              <th mat-header-cell *matHeaderCellDef>Generated At</th>
              <td mat-cell *matCellDef="let report">
                <div class="date-cell">
                  <span class="date">{{ report.generatedAt | date:'mediumDate' }}</span>
                  <span class="time">{{ report.generatedAt | date:'shortTime' }}</span>
                </div>
              </td>
            </ng-container>

            <ng-container matColumnDef="generatedBy">
              <th mat-header-cell *matHeaderCellDef>Generated By</th>
              <td mat-cell *matCellDef="let report">
                <div class="user-cell">
                  <strong>{{ report.generatedByUserName }}</strong>
                  <span class="email-address">{{ report.createdBy }}</span>
                  <span class="user-id">ID: {{ report.generatedByUserId }}</span>
                </div>
              </td>
            </ng-container>

            <ng-container matColumnDef="district">
              <th mat-header-cell *matHeaderCellDef>District</th>
              <td mat-cell *matCellDef="let report">
                <div class="district-cell">
                  <span class="district">{{ report.districtName || 'N/A' }}</span>
                  <span class="division">{{ report.divisionName }}</span>
                </div>
              </td>
            </ng-container>

            <ng-container matColumnDef="counts">
              <th mat-header-cell *matHeaderCellDef>Summary (P/R/T)</th>
              <td mat-cell *matCellDef="let report">
                <div class="counts-strip">
                  <span class="count-pill passed" matTooltip="Passed">{{ report.passedCount }}</span>
                  <span class="count-pill rejected" matTooltip="Deffered">{{ report.rejectedCount }}</span>
                  <span class="count-pill total" matTooltip="Total">{{ report.totalApps }}</span>
                </div>
              </td>
            </ng-container>

            <ng-container matColumnDef="status">
              <th mat-header-cell *matHeaderCellDef>Status</th>
              <td mat-cell *matCellDef="let report">
                <span class="status-badge" [ngClass]="report.status?.toLowerCase().replace('_', '-')">
                  <mat-icon>{{ getStatusIcon(report.status) }}</mat-icon>
                  <span>{{ report.status?.split('_')?.join(' ') || 'DRAFT' }}</span>
                </span>
              </td>
            </ng-container>

            <ng-container matColumnDef="actions">
              <th mat-header-cell *matHeaderCellDef></th>
              <td mat-cell *matCellDef="let report" class="actions-cell">
                <button mat-icon-button (click)="viewReport(report)" matTooltip="View Summary" class="action-btn">
                   <mat-icon>show_chart</mat-icon>
                 </button>
                 
                 <button mat-flat-button *ngIf="canGenerateBill() && report.status === 'SUBMITTED'" 
                         class="bill-btn-luxe" (click)="generateBill(report)">
                    <mat-icon>receipt_long</mat-icon>
                    <span>Generate Bill</span>
                 </button>

                 <button mat-stroked-button (click)="viewApplications(report)" class="apps-btn-luxe">
                   <mat-icon ripple>grid_view</mat-icon>
                   <span>Apps</span>
                 </button>
              </td>
            </ng-container>

            <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
            <tr mat-row *matRowDef="let row; columns: displayedColumns;" (click)="viewReport(row)" class="clickable-row"></tr>
          </table>

          <div class="empty-state" *ngIf="reports().length === 0 && !isLoading()">
            <mat-icon>find_in_page</mat-icon>
            <p>No reports found matching your search.</p>
          </div>

          <mat-paginator [length]="totalRecords"
                         [pageSize]="pageSize"
                         [pageSizeOptions]="[5, 10, 25, 50]"
                         (page)="onPageChange($event)"
                         aria-label="Select page">
          </mat-paginator>
        </div>
      </div>
    </div>
  `,
  styles: [`
    @keyframes slideIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }

    .reports-container {
      padding: 0; background: #f8fafc; min-height: 100vh;
      animation: slideIn 0.5s ease-out; font-family: 'Inter', sans-serif;
    }

    .glass-header {
      background: rgba(255, 255, 255, 0.8); backdrop-filter: blur(20px);
      padding: 32px 40px; border-bottom: 1px solid rgba(0,0,0,0.05);
      top: 0; z-index: 100;
      
      .header-content {
        display: flex; justify-content: space-between; align-items: center;
        max-width: 1400px; margin: 0 auto;
      }

      .title-section {
        display: flex; align-items: center; gap: 20px;
        .feature-icon {
          width: 56px; height: 56px; background: #0f172a; color: white;
          display: flex; align-items: center; justify-content: center;
          border-radius: 18px; font-size: 32px; box-shadow: 0 10px 20px rgba(15,23,42,0.15);
        }
        .text-group {
          h1 { margin: 0; font-size: 28px; font-weight: 900; color: #0f172a; letter-spacing: -0.5px; }
          p { margin: 4px 0 0; color: #64748b; font-size: 14px; font-weight: 500; }
        }
      }

      .search-box {
        background: #f1f5f9; border-radius: 16px; padding: 0 20px;
        display: flex; align-items: center; gap: 12px;
        width: 320px; height: 52px; border: 2px solid transparent; transition: all 0.3s ease;
        &:focus-within { border-color: #3b82f6; background: white; box-shadow: 0 10px 30px rgba(59,130,246,0.1); }
        mat-icon { color: #94a3b8; font-size: 20px; }
        input { border: none; background: transparent; outline: none; width: 100%; font-size: 14px; font-weight: 600; color: #1e293b; }
      }
    }

    .content-area {
      max-width: 1400px; margin: 0 auto; padding: 40px;
    }

    .table-card {
      background: white; border-radius: 28px; overflow: hidden;
      box-shadow: 0 20px 60px rgba(0,0,0,0.03); border: 1px solid rgba(0,0,0,0.04);
      position: relative;
    }

    .luxe-table {
      width: 100%; transition: opacity 0.3s ease;
      &.loading-fade { opacity: 0.5; pointer-events: none; }
      th { background: #fafafa; padding: 20px 24px; font-size: 11px; font-weight: 800; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }
      td { padding: 20px 24px; border-bottom: 1px solid #f1f5f9; }
      
      .clickable-row {
        cursor: pointer; transition: background 0.2s ease;
        &:hover { background: #f8fafc; }
      }

      .report-id {
        display: flex; align-items: center; gap: 8px;
        .prefix { background: #0f172a; color: white; font-size: 10px; font-weight: 900; padding: 2px 6px; border-radius: 4px; }
        strong { font-size: 15px; color: #0f172a; }
      }

      .date-cell, .user-cell {
        display: flex; flex-direction: column;
        strong { font-size: 14px; color: #1e293b; }
        span { font-size: 12px; color: #64748b; }
        .date { font-weight: 700; color: #1e293b; }
        .time { font-size: 11px; }
      }

      .counts-strip {
        display: flex; gap: 6px;
        .count-pill {
          padding: 4px 10px; border-radius: 8px; font-size: 12px; font-weight: 800;
          &.passed { background: #dcfce7; color: #10b981; }
          &.rejected { background: #fee2e2; color: #ef4444; }
          &.total { background: #f1f5f9; color: #475569; }
        }
      }

      .status-badge {
        display: inline-flex; align-items: center; gap: 8px; padding: 6px 12px; border-radius: 10px; font-size: 11px; font-weight: 900;
        background: #f1f5f9; color: #64748b; white-space: nowrap; transition: all 0.3s ease;
        line-height: 1; min-height: 32px;
        mat-icon { font-size: 18px; width: 18px; height: 18px; flex-shrink: 0; }
        span { display: inline-flex; align-items: center; } /* For vertical centering */
        
        &.submitted { background: #ecfdf5; color: #059669; border: 1.5px solid #dcfce7; }
        &.sent-to-convener { background: #eff6ff; color: #2563eb; border: 1.5px solid #dbeafe; }
        &.approved { background: #f0fdf4; color: #166534; border: 1.5px solid #bbf7d0; }
        &.rejected-by-convener { background: #fef2f2; color: #991b1b; border: 1.5px solid #fecaca; }
        &.draft { background: #f8fafc; color: #475569; border: 1.5px solid #e2e8f0; }
      }

      .district-cell {
        display: flex; flex-direction: column;
        .district { font-size: 13px; font-weight: 700; color: #1e293b; }
        .division { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.5px; }
      }

      .email-address {
        font-size: 11px !important;
        color: #3b82f6 !important;
        margin: 2px 0;
      }

      .user-id {
        opacity: 0.6;
        font-size: 10px !important;
      }

      .actions-cell { 
        text-align: right; 
        white-space: nowrap; 
        display: flex;
        align-items: center;
        justify-content: flex-end;
        gap: 4px;
      }
      .action-btn { 
        color: #64748b; width: 40px; height: 40px; 
        display: flex; align-items: center; justify-content: center; 
        transition: all 0.2s;
        &:hover { color: #3b82f6; background: #eff6ff; } 
      }
      .apps-btn-luxe {
        height: 40px; border-radius: 12px; border: 1.5px solid #e2e8f0; color: #475569; font-weight: 700; font-size: 13px;
        transition: all 0.3s ease; display: inline-flex; align-items: center; padding: 0 16px;
        mat-icon { font-size: 18px; width: 18px; height: 18px; margin-right: 6px; }
        &:hover { background: #0f172a; color: white; border-color: #0f172a; transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
      }
      .bill-btn-luxe {
        height: 40px; border-radius: 12px; background: #10b981; color: white; font-weight: 700; font-size: 13px;
        margin: 0 4px; transition: all 0.3s ease; border: none; padding: 0 16px; display: inline-flex; align-items: center;
        mat-icon { font-size: 18px; width: 18px; height: 18px; margin-right: 6px; }
        &:hover { background: #059669; transform: translateY(-2px); box-shadow: 0 4px 12px rgba(16,185,129,0.3); }
      }
    }

    .empty-state {
      padding: 80px 0; text-align: center; color: #94a3b8;
      mat-icon { font-size: 64px; width: 64px; height: 64px; margin-bottom: 16px; }
      p { font-size: 16px; font-weight: 600; }
    }

    ::ng-deep .mat-mdc-paginator {
      background: #fafafa !important; border-top: 1px solid #f1f5f9;
    }
  `]
})
export class QualityInspectionReportsComponent implements OnInit {
  private reportService = inject(InspectionQICReportService);
  private router = inject(Router);
  private authService = inject(AuthService);

  canGenerateBill = computed(() => this.authService.hasFeature('/portal/quality-inspection/reports/bill'));

  reports = signal<InspectionQICReportPayload[]>([]);
  isLoading = signal<boolean>(false);
  totalRecords = 0;
  pageSize = 10;
  currentPage = 0;
  searchQuery = '';

  private searchSubject = new Subject<string>();
  displayedColumns: string[] = ['reportNo', 'generatedAt', 'generatedBy', 'district', 'counts', 'status', 'actions'];

  ngOnInit() {
    this.setupSearch();
    this.loadReports();
  }

  private setupSearch() {
    this.searchSubject.pipe(
      debounceTime(500),
      distinctUntilChanged()
    ).subscribe(() => {
      this.currentPage = 0;
      this.loadReports();
    });
  }

  onSearchChange() {
    this.searchSubject.next(this.searchQuery);
  }

  loadReports() {
    this.isLoading.set(true);
    this.reportService.getAllReports(this.searchQuery, this.currentPage, this.pageSize)
      .pipe(finalize(() => this.isLoading.set(false)))
      .subscribe({
        next: (page: any) => {
          this.reports.set(page.content);
          this.totalRecords = page.totalElements;
        },
        error: (err) => {
          console.error('Failed to load reports', err);
        }
      });
  }

  onPageChange(event: PageEvent) {
    this.pageSize = event.pageSize;
    this.currentPage = event.pageIndex;
    this.loadReports();
  }

  viewReport(report: InspectionQICReportPayload) {
    this.router.navigate(['/portal/quality-inspection/inspection-report-view'], {
      state: { report },
      queryParams: { id: report.id }
    });
  }

  viewApplications(report: InspectionQICReportPayload) {
    this.router.navigate(['/portal/quality-inspection/inspection-report-view'], {
      state: { report },
      queryParams: { id: report.id, view: 'cards' }
    });
  }

  generateBill(report: InspectionQICReportPayload) {
    this.router.navigate(['/portal/quality-inspection/inspection-report-view'], {
      state: { report },
      queryParams: { id: report.id, action: 'print-bill' }
    });
  }

  getStatusIcon(status?: string): string {
    if (!status) return 'edit_note';
    const s = status.toUpperCase().replace(/ /g, '_');
    switch (s) {
      case 'SUBMITTED': return 'verified';
      case 'SENT_TO_CONVENER': return 'forward_to_inbox';
      case 'APPROVED': return 'task_alt';
      case 'REJECTED_BY_CONVENER': return 'gpp_bad';
      case 'DRAFT': return 'edit_note';
      default: return 'info';
    }
  }
}
